### ISSUE TITLE
Release 7-Zip file incompatible with py7zr

### ISSUE THREAD

**Issue by amstelchen** [ianpatt/f4se#24]
Guys, on the next upcoming update of F4SE, could you compress the 7-Zip archive with only level 7 (Maximum) instead on 9 (Ultra) compression? 7-Zip then would use BCJ instead of BCJ2 compression and that would make it easier to open the archive file using a Python script I am trying to use.

Context: https://github.com/miurahr/py7zr/discussions/560, https://github.com/miurahr/py7zr/issues/511, https://github.com/miurahr/py7zr/issues/100

**Comment by ianpatt** [comment]
I'm sorry, but this is an issue to report to your library developer. The issues you have linked do not show any technical reasons for not supporting the BCJ2 filter, just that the core python lzma library doesn't support it. BCJ2 has been around since 2001-11-04 according to https://7-zip.org/history.txt.

Currently that part of the release process is not automated, but generating a file that is small as possible is important when you need to pay for bandwidth.
